### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by shim94kr** [ktertikas/part_nerf#1]
Congratulations on having your paper accepted for CVPR 2023!

May I know when the code is available?

**Comment by ktertikas** [comment]
Hi, thanks for the interest in our work! We are planning to release the code in May. Thank you for your patience!

**Comment by shim94kr** [comment]
Hello, @ktertikas!

Thank you for the response.

Any updates on this? May is over, and June is starting!

**Comment by ktertikas** [comment]
Hi @shim94kr , the code is now released, sorry for the delay!
