### ISSUE TITLE
None in the split_file

### ISSUE THREAD

**Issue by Zhiyuan-R** [ktertikas/part_nerf#3]
Thanks for releasing this excellent work!

But when I try to run the training code with lego dataset by the command line below:

`python train_partnerf.py config="../conf/partnerf_lego.yaml"`

I get the error report like this:

<img width="900" alt="image" src="https://github.com/ktertikas/part_nerf/assets/112899820/3420e0a3-8993-418b-9a69-ac7091c6f3e7">

I also check the split file and I find that is hard to understand for me.

Could you help me with this! Thanks again!

**Comment by ktertikas** [comment]
Hi, 

I am not totally sure what is causing this from this specific error log, but my guess would be that the split files have not been downloaded properly. The csv files are stored as Git LFS objects in Github, so you will need to run `git lfs install`  before fetching the files. Just to make sure that you have the correct files downloaded, you should be able to see something like this on the first lines of the `new_tractor.csv` file:

```
id,sequence_id,split
new_tractor,00000,train
new_tractor,00001,train
new_tractor,00002,train
```

Let me know if this solves your issue!

**Comment by Zhiyuan-R** [comment]
Wow! problem solved! I have successfully trained my first scene (lego)! Thanks for your helpful response!
