### ISSUE TITLE
slightly bad mesh results by default training script.

### ISSUE THREAD

**Issue by Zhiyuan-R** [ktertikas/part_nerf#4]
Dear Author,

Thanks for your nice work and excellent codebase.

I trained my first scene successfully with the default lego setting. 

But when I visualize the results, I get the figure below:

![image](https://github.com/ktertikas/part_nerf/assets/112899820/0d75e7ad-4ee9-465f-996f-c2d3adce66d7)

Do you know why the result is not that good? Or it should be in this way.

Best,
Zhiyuan

**Comment by Zhiyuan-R** [comment]
Figure from another view!

![image](https://github.com/ktertikas/part_nerf/assets/112899820/9dc9d49d-3fdf-43e6-ab0f-3d7abb20490a)

**Comment by ktertikas** [comment]
Hi @Zhiyuan-VisionKing , there are two things here:
1. The inference script should be ran with the option `--padding 2.0`. This would solve the issue why your reconstruction seems to be cut.
2. There may be a case that the training needs a bit more time, but let's first check the output mesh with the correct reconstruction setting (padding) before jumping to that!

**Comment by Zhiyuan-R** [comment]
Wow! After taking your first suggestion, guess what? I get the perfect results!

![image](https://github.com/ktertikas/part_nerf/assets/112899820/4c8d23e7-d43a-4d3f-a279-ac817b0c24de)

**Comment by ktertikas** [comment]
Yeah, it's looking much better now! I am closing this issue for now, feel free to reopen or create a new issue if something else arises!
