### ISSUE TITLE
Part-NeRF without mask labels

### ISSUE THREAD

**Issue by Zhiyuan-R** [ktertikas/part_nerf#5]
Dear Authors,

I hope to ask how this model will perform if there is no mask labels.

As far as I know, this will affect the mask loss, occupancy loss and coverage loss.

Will it lead to the failure of training totally?

Best,
Zhiyuan

**Comment by ktertikas** [comment]
Our method currently uses mask labels, and it is very important for the refinement of the object boundaries. Another issue that comes when removing the masks is that you cannot do equal sampling for rays inside and outside of the object, something that makes the training more stable.
