### ISSUE TITLE
How to get m parts of a object

### ISSUE THREAD

**Issue by zhirui-gao** [ktertikas/part_nerf#6]
Hi, awesome work!  I have a question, are the m parts of the object pre-segmented, and how is it done?

**Comment by ktertikas** [comment]
Hi @zhirui-gao , thanks for the interest in our work!

The M parts of the object are not pre-segmented as there are no part labels, they are learned in an unsupervised fashion. The losses responsible for learning meaningful parts are the coverage, overlapping, and control losses (equations 21, 22, 23 of the [main paper](https://arxiv.org/pdf/2303.09554.pdf)). 

Closing this for now, feel free to reopen if there are more questions!

**Comment by zhirui-gao** [comment]
I understand, thank you for your reply

**Comment by zhirui-gao** [comment]
> Hi @zhirui-gao , thanks for the interest in our work!
> 
> The M parts of the object are not pre-segmented as there are no part labels, they are learned in an unsupervised fashion. The losses responsible for learning meaningful parts are the coverage, overlapping, and control losses (equations 21, 22, 23 of the [main paper](https://arxiv.org/pdf/2303.09554.pdf)).
> 
> Closing this for now, feel free to reopen if there are more questions!

In the coverage loss, it calculates a binary cross-entropy loss between the predicted per-part and target labels. How to get the target labels?
Thanks for your reply

**Comment by ktertikas** [comment]
We are using 2D object masks as supervision, and the target labels are the mask values for each pixel / ray!
