### ISSUE TITLE
Model trained on Lego dataset fail on inference using default configuration file

### ISSUE THREAD

**Issue by sicheng2020** [ktertikas/part_nerf#8]
Hi, I tried to train on Lego dataset using the default configuration file. Then I used the model to run inference and the generated Lego images are very blury and the size and the scaling is not [correct[](url)](url)
![img_0000_000](https://github.com/ktertikas/part_nerf/assets/60579289/bae56f3d-5e2b-4f7f-9114-76563542ecf9)
Could you please provide the pretrained model of Lego or the configuration file including training details on Lego? Thanks!

**Comment by ktertikas** [comment]
Hi @sicheng2020 , the configuration file for training the Lego dataset should be working fine. You probably need to set the `--padding 2.0` option in the inference script (related to issue https://github.com/ktertikas/part_nerf/issues/4 - now pinned)! Closing for now, let me know if you still have issues!

Best,
Konstantinos
