### ISSUE TITLE
Training with mask

### ISSUE THREAD

**Issue by GuHuangAI** [ktertikas/part_nerf#9]
Hello, I don't see there are masks in the proposed NeRF datasets.
How do you get the 2D part mask of each object, or the 2D mask is of the whole object but not part-aware?

**Comment by ktertikas** [comment]
Hi, our method does not require part masks, but rather learns the part arangements in an unsupervised way. The training only requires whole object 2D masks!

**Comment by GuHuangAI** [comment]
Thanks a lot！
